name: Notification Helper
description: Sends a Slack notification based on the current job status
inputs:
  failed:
    description: string
    default: 'true'
  release_kind:
    description: string
  release_title:
    description: string
  deploy_icon:
    description: string
  deploy_name:
    description: string
  deploy_link:
    description: string
  slack_webhook:
    description: string
    required: true

runs:
  using: composite
  steps:
    - run: |
        echo SLACK_CHANNEL=devops-${{ inputs.release_kind == 'production' && 'prd' || 'nonprd' }} >> $GITHUB_ENV
        echo SLACK_ICON='${{ inputs.deploy_icon }}' >> $GITHUB_ENV
        echo SLACK_USERNAME='${{ inputs.name }}' >> $GITHUB_ENV
        echo SLACK_WEBHOOK='${{ inputs.slack_webhook }}' >> $GITHUB_ENV
      shell: bash

    - name: Report success
      uses: rtCamp/action-slack-notify@v2
      if: inputs.failed != 'true'
      env:
        SLACK_TITLE: "Deployed ${{ inputs.deploy_name }} (${{ inputs.release_title }})"
        SLACK_FOOTER: ${{ inputs.deploy_link }}
        MSG_MINIMAL: ref,commit

    - name: Report failure
      uses: rtCamp/action-slack-notify@v2
      if: inputs.failed == 'true'
      env:
        SLACK_COLOR: '#FF0000' # red
        SLACK_TITLE: "Failed to deploy ${{ inputs.deploy_name }} (${{ inputs.release_title }})"
        SLACK_FOOTER: Deployment failed!
