name: Notification Helper
description: Sends a Slack notification based on the current job status

runs:
  using: composite
  steps:
    - name: Report success
      uses: rtCamp/action-slack-notify@v2
      if: success()
      env:
        SLACK_CHANNEL: devops-${{ inputs.release_kind == 'production' && 'prd' || 'nonprd' }}
        SLACK_ICON: ${{ inputs.deploy_icon }}
        SLACK_USERNAME: ${{ inputs.name }}
        SLACK_TITLE: "Deployed ${{ inputs.deploy_name }} (${{ inputs.release_title }})"
        SLACK_WEBHOOK: ${{ secrets.slack_webhook }}
        SLACK_FOOTER: ${{ inputs.deploy_link }}
        MSG_MINIMAL: ref,commit

    - name: Report failure
      uses: rtCamp/action-slack-notify@v2
      if: failure()
      env:
        SLACK_CHANNEL: devops-${{ inputs.release_kind == 'production' && 'prd' || 'nonprd' }}
        SLACK_ICON: ${{ inputs.deploy_icon }}
        SLACK_USERNAME: ${{ inputs.name }}
