name: mytest
on:
  workflow_dispatch:

jobs:
  mytest:
    runs-on: ubuntu-latest
    steps:
    - uses: th0th/notify-discord@v0.4.1
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_JOB_NAME: "Build and deploy"
        GITHUB_JOB_STATUS: ${{ job.status }}
