name: mytest
on:
  pull_request:
    types: [ ready_for_review, reopened ]
    paths:
      - "**.ts"
      - ".github/workflows/**"
      - "!**.md"
  push:
    branches:
      - "**"
    tags:
      - "release-*"
    paths:
      - "**.ts"
      - ".github/workflows/**"
      - "!**.md"

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo one
      - uses: actions/checkout@v3

      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"

      - uses: ./.github/workflows/scripts/release-helper

      - run: 'true'


    outputs:
      release_kind: ${{ env.RELEASE_KIND }}

  two:
    needs: run-ui-tests
    if: >-
      contains(needs.run-ui-tests.outputs.release_targets, 'web-messenger')
      || needs.run-ui-tests.outputs.release_kind == 'staging'
      || needs.run-ui-tests.outputs.release_kind == 'preview'
    runs-on: ubuntu-latest
    steps:
      - run: echo two
