name: mytest
on:
  push:

jobs:
  one:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'release-')
    runs-on: ubuntu-latest
    steps:
      - run: echo one

  two:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: echo two

  three:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo three

  helper:
    uses: ./.github/workflows/release-helper.yml

  final:
    if: '!failure()'
    needs: [one, two, three, helper]
    runs-on: ubuntu-latest
    steps:
      - run: echo final
      - run: echo 'barf sees ${{ needs.helper.outputs.kind.name }} as ${{ needs.helper.outputs.kind.abbrev }} '