name: mytest
on:
  push:

jobs:
  one:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'release-')
    runs-on: ubuntu-latest
    steps:
      - run: echo one

  two:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: echo two
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/scripts/release-helper
        id: helper
      - run: echo 'barf sees ${{ steps.helper.outputs.barf }}'

  three:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo three

  # final:
  #   if: '!failure()'
  #   needs: [one, two, three]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo final
  #     - run: echo 'barf sees ${{ env.RELEASE_KIND }} as ${{ env.RELEASE_ABBREV }}'
