name: mytest
on:
  push:
    branches:
      - "**"
    tags:
      - "release-*"
    paths:
      - "**.ts"
      - ".github/workflows/**"
      - "!**.md"

jobs:
  one:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'release-')
    runs-on: ubuntu-latest
    steps:
      - run: echo one

  # release:
  #   needs: one
  #   uses: ./.github/workflows/release-manager.yml
  #   with:
  #     name: barf
  #   secrets:
  #     slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  two:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: echo two
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/scripts/release-helper
      - run: 'true'
      - run: cat foo
    outputs:
      release_env: ${{ env.RELEASE_ENV }}

  rand:
    needs: two
    runs-on: ubuntu-latest
    steps:
      - run: echo 'barf sees ${{ needs.two.outputs.release_env }}'

  # three:
  #   if: github.event_name == 'pull_request'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo three

  release:
    needs: two
    if: success() || failure()
    uses: ./.github/workflows/release-manager.yml
    with:
      name: barf
      failed: ${{ needs.two.result == 'failure' }}
      release_env: ${{ needs.two.outputs.release_env }}
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
