name: mytest
on:
  push:
    branches:
      - "**"
    tags:
      - "release-*"
    paths:
      - "**.ts"
      - ".github/workflows/**"
      - "!**.md"

jobs:
  one:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'release-')
    runs-on: ubuntu-latest
    steps:
      - run: echo one

  # release:
  #   needs: one
  #   uses: ./.github/workflows/release-manager.yml
  #   with:
  #     name: barf
  #   secrets:
  #     slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  two:
    if: github.ref_name == 'main2'
    runs-on: ubuntu-latest
    steps:
      - run: echo two
      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"
      # - run: cat foo

  three:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo three

  notify:
    needs: [one, two, three]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo SUCCEEDED=${{ needs.one.result == 'success'
                          || needs.two.result == 'success'
                          || needs.three.result == 'success' }} >> $GITHUB_ENV
          echo FAILED=${{ needs.one.result == 'failure'
                       || needs.two.result == 'failure'
                       || needs.three.result == 'failure' }} >> $GITHUB_ENV
      - uses: actions/checkout@v3
        if: env.SUCCEEDED == 'true' || env.FAILED == 'true'
      - uses: ./.github/workflows/scripts/notification-helper
        if: env.SUCCEEDED == 'true' || env.FAILED == 'true'
        with:
          failed: ${{ env.FAILED }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
