name: mytest
on:
  pull_request:
    paths:
      - "**.ts"
      - ".github/workflows/**"
      - "!**.md"
  push:
    branches:
      - "**"
    tags:
      - "release-*"
    paths:
      - "**.ts"
      - ".github/workflows/**"
      - "!**.md"

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env

      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"

      # - name: Check for open pull requests
      #   run: |
      #     if gh pr list --state open --head "$(git rev-parse --abbrev-ref HEAD)"; then
      #       echo 'pr_open=true' >> $GITHUB_OUTPUT
      #     else
      #       echo 'pr_open=false' >> $GITHUB_OUTPUT
      #     fi

  run-ui-tests:
    needs: check-pr
    # if: needs.check-pr.outputs.
    runs-on: ubuntu-latest
    steps:
      - run: echo one
      - uses: actions/checkout@v3

      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"

      - uses: ./.github/workflows/scripts/release-helper
      - run: 'true'


      # - uses: trunk-io/breakpoint@v1
      #   with:
      #     breakpoint-id: break
      #     run: true
      #     trunk-token: ${{ secrets.TRUNK_REPO_TOKEN }}

    outputs:
      release_kind: ${{ env.RELEASE_KIND }}

  barf:
    needs: run-ui-tests
    if: needs.run-ui-tests.outputs.barf == 'i-was-here'
    runs-on: ubuntu-latest
    steps:
      - run: echo yes

  two:
    needs: run-ui-tests
    if: >-
      contains(needs.run-ui-tests.outputs.release_targets, 'web-messenger')
      || needs.run-ui-tests.outputs.release_kind == 'staging'
      || needs.run-ui-tests.outputs.release_kind == 'preview'
    runs-on: ubuntu-latest
    steps:
      - run: echo two
