name: mytest
on:
  push:
    branches:
      - "**"
    tags:
      - "release-*"
    paths:
      - "**.ts"
      - ".github/workflows/**"
      - "!**.md"

jobs:
  one:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'release-')
    runs-on: ubuntu-latest
    steps:
      - run: echo one

  # release:
  #   needs: one
  #   uses: ./.github/workflows/release-manager.yml
  #   with:
  #     name: barf
  #   secrets:
  #     slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  two:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: echo two
      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"
      - run: cat foo

  three:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo three

  notify:
    if: '!cancelled()'
    needs: [one, two, three]
    uses: ./.github/workflows/notification-manager.yml
    with:
      succeeded: ${{ success() }}
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
