name: mytest
on:
  push:
    branches:
      - "**"
    tags:
      - "release-*"
    paths:
      - "**.ts"
      - ".github/workflows/**"
      - "!**.md"

jobs:
  one:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'release-')
    runs-on: ubuntu-latest
    steps:
      - run: echo one
      # - uses: actions/checkout@v3
      # - uses: ./.github/workflows/scripts/release-helper

  release:
    needs: one
    uses: ./.github/workflows/release-manager.yml
    with:
      name: barf
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  two:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: echo two
      - run: |
          echo 'FOO<<EOF' >> $GITHUB_ENV
          echo 'one' >> $GITHUB_ENV
          echo 'two' >> $GITHUB_ENV
          echo 'three' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: test

  three:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo three

  # final:
  #   if: '!failure()'
  #   needs: [one, two, three]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo final
  #     - run: echo 'barf sees ${{ env.RELEASE_KIND }} as ${{ env.RELEASE_ABBREV }}'
