name: mytest
on:
  push:
    branches:
      - "**"
    tags:
      - "release-*"
    paths:
      - "**.ts"
      - ".github/workflows/**"
      - "!**.md"

jobs:
  one:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'release-')
    runs-on: ubuntu-latest
    steps:
      - run: echo one
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/scripts/release-helper
      - run: 'true'
    outputs:
      release_env: ${{ env.RELEASE_ENV }}

  release-one:
    needs: one
    if: success() || failure()
    uses: ./.github/workflows/release-manager.yml
    with:
      name: barf-one
      deploy_icon: https://www.maxpixel.net/static/photo/2x/Ethereum-Icon-Ethereum-Ethereum-Logo-Ethereum-Symbol-6278328.png
      failed: ${{ needs.one.result == 'failure' }}
      release_env: ${{ needs.one.outputs.release_env }}
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  two:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: echo two
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/scripts/release-helper
      - run: 'true'
      # - run: cat foo
    outputs:
      release_env: ${{ env.RELEASE_ENV }}

  release-two:
    needs: two
    if: success() || failure()
    uses: ./.github/workflows/release-manager.yml
    with:
      name: barf-two
      deploy_icon: https://cdn.pixabay.com/photo/2021/05/24/09/15/ethereum-logo-6278328_960_720.png
      deploy_link: http://app.3num.co
      failed: ${{ needs.two.result == 'failure' }}
      release_env: ${{ needs.two.outputs.release_env }}
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
