name: mytest
on:
  push:
    branches:
      - "**"
    tags:
      - "release-*"
    paths:
      - "**.ts"
      - ".github/workflows/**"
      - "!**.md"

jobs:
  one:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'release-')
    runs-on: ubuntu-latest
    steps:
      - run: echo one
      - run: echo "${{ toJson(github) }}" | jq

  # release:
  #   needs: one
  #   uses: ./.github/workflows/release-manager.yml
  #   with:
  #     name: barf
  #   secrets:
  #     slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  two:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: echo two
      - run: echo "${{ toJson(github) }}"
      - run: cat foo

  three:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo three

  final:
    if: 'failure()'
    needs: [one, two, three]
    runs-on: ubuntu-latest
    steps:
      - run: echo final
      # - uses: rtCamp/action-slack-notify@v2
