name: Notification Manager
on:
  workflow_run:
    workflows:
      - "**"
    types: [completed]

jobs:
  success:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - run: echo 'The triggering workflow passed'
  failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - run: echo 'The triggering workflow failed'
