name: Notification Manager
on:
  workflow_run:
    workflows:
      - "**"
    types: [completed]

jobs:
  report-success:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - run: echo 'The triggering workflow passed'
      - run: echo '${{ github.event.workflow }}'
      - run: echo '${{ github.event.workflow_run }}'

  report-failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - run: echo 'The triggering workflow failed'
      - run: echo '${{ github.event.workflow }}'
      - run: echo '${{ github.event.workflow_run }}'

