name: PR Closed
on:
  pull_request:
    types: [closed]

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR changes
        id: check
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const files = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            let hasMobileKeyChanges = true;
            const modifiedFilesInSubdirectory = files.data.forEach(file => {
              console.log('barf', file.filename);
              if (file.filename.match(/^(lib|web|svr)-mobilekey\//)) {
                hasMobileKeyChanges = true;
              }
            });

            core.setOutput('mobilekey', hasMobileKeyChanges ? 'cleanup' : '');
    outputs:
      mobilekey: ${{ steps.check.outputs.mobilekey }}

  mobilekey_cleanup:
    needs: check_changes
    if: needs.check_changes.outputs.mobilekey == 'cleanup'
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"
      - uses: actions/checkout@v3
      - run: echo 'mobilekey cleanup!!'
      - uses: ./.github/workflows/scripts/release-helper
      - run: echo "barf is ${{ env.RELEASE_PR_NUMBER }}"
