name: Release Helper
on:
  # invoked from other workflows
  workflow_call:
    outputs:
      kind:
        description: The kind of release
        value: ${{ env.RELEASE_KIND }}
      abbrev:
        description: An abbreviation of the kind of release
        value: ${{ env.RELEASE_ABBREV }}

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate state of ${{ github.ref_name }}
        run: |
          if [ ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'release-prd-') }} = true ]; then
            kind=production
            abbrev=prd
          elif [ ${{ github.ref_type == 'branch' && github.ref_name == 'main' }} = true ]; then
            kind=staging
            abbrev=stg
          elif [ ${{ github.event_name == 'pull_request' }} = true ]; then
            kind=preview
            abbrev=pre
          else
            kind=other
            abbrev=oth
          fi
          echo "RELEASE_KIND=${kind}" >> $GITHUB_ENV
          echo "RELEASE_ABBREV=${abbrev}" >> $GITHUB_ENV
