name: simple
on:
  workflow_dispatch:
    inputs:
      skip:
        description: skip match
        required: false
      fail:
        description: fail match
        required: false

jobs:
  one:
    if: ${{ inputs.skip != 'one' }}
    runs-on: ubuntu-latest
    steps:
    - run: test '${{ inputs.fail }}' != one

    - uses: sarisia/actions-status-discord@v1
      if: ${{ always() && !success() }}
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: 'failed!!!'

  two:
    if: ${{ inputs.skip != 'two' }}
    needs: one
    runs-on: ubuntu-latest
    steps:
    - run: test '${{ inputs.fail }}' != two

    - uses: sarisia/actions-status-discord@v1
      if: ${{ always() && !success() }}
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: 'failed!!!'

  three:
    needs: two
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
