name: simple
on:
  pull_request:
    types: [ ready_for_review, reopened ]
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install --immutable

      - uses: ./.github/workflows/scripts/release-helper
      - uses: ./.github/workflows/scripts/netlify

    outputs:
      short_id: ${{ env.SHORT_ID }}
      deploy_link: ${{ env.DEPLOY_LINK }}

  # release:
  #   needs: build
  #   uses: ./.github/workflows/release-manager.yml
  #   with:
  #     name: floofy
  #     deploy_name: floofy container ${{ needs.build.outputs.short_id }}
  #     deploy_link: ${{ needs.build.outputs.deploy_link }}
  #   secrets:
  #     slack_webhook: ${{ secrets.RELEASE_SLACK_WEBHOOK }}
