name: simple
on:
  push:
    tags:
      - "v*.*.*-barf.*"
  workflow_dispatch:
    inputs:
      skip:
        description: skip match
        required: false
      fail:
        description: fail match
        required: false

jobs:
  one:
    if: ${{ inputs.skip != 'one' }}
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.release.outputs.url }}
    steps:
    - run: test '${{ inputs.fail }}' != one

    - id: release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: false

    - uses: sarisia/actions-status-discord@v1
      if: ${{ always() && !success() }}
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: 'failed!!!'

  two:
    if: ${{ inputs.skip != 'two' }}
    needs: one
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ needs.one.outputs.release_url }}
    steps:
    - run: test '${{ inputs.fail }}' != two

    - uses: sarisia/actions-status-discord@v1
      if: ${{ always() && !success() }}
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: 'failed!!!'

  three:
    needs: two
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: Released ${{ needs.two.outputs.release_url }}
