name: simple
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "name=hello-${RANDOM}" >> $GITHUB_OUTPUT
        id: tag

      - run: echo "barf sees ref=${{ github.ref }} name=${{ github.ref_name }}"

      - run: env

      # - run: git tag "${{ steps.tag.outputs.name }}"
      # - run: git push --tags
      # - run: gh release create "${{ steps.tag.outputs.name }}"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
