name: simple
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "name=hello-${RANDOM}" >> $GITHUB_OUTPUT
        id: tag

      - run: echo "barf sees ref=${{ github.ref }} name=${{ github.ref_name }}"

      - run: echo "APP_NAME=lessor-stg" >> $GITHUB_ENV
      - run: env

      - run: >-
          heroku releases:info -a $APP_NAME --json > relinfo.json
          && cat relinfo.json
        env:
          HEROKU_API_KEY: ${{ secrets.LESSOR_HEROKU_API_KEY }}

      - run: echo "FULL_ID=$(cat relinfo.json | jq -r .id)" >> $GITHUB_ENV
      - run: echo "SHORT_ID=$(echo $FULL_ID | cut -d- -f1)" >> $GITHUB_ENV

      - run: echo "barf sees $SHORT_ID and $FULL_ID"

    # outputs:
    #   full_id: ${{ env.FULL_ID }}

  # silly:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "barf got ${{ needs.build.outputs.full_id }}"

  release:
    needs: build
    uses: ./.github/workflows/release-manager.yml
    with:
      message: Lessor deployed as ${{ env.SHORT_ID }}
      deploy_icon: https://brand.heroku.com/static/media/heroku-logo-stroke-gradient.bb410472.svg
      deploy_link: https://dashboard.heroku.com/apps/lessor-stg/activity/releases/ceb927dd-bef1-4edf-b7bc-12484b0a6fba
    secrets:
      slack_webhook: ${{ secrets.RELEASE_SLACK_WEBHOOK }}

  # fake-web-ui:
  #   needs: build
  #   uses: ./.github/workflows/release-manager.yml
  #   with:
  #     message: web-ui deployed as ${{ github.sha }}
  #     deploy_icon: https://saasvideos.io/wp-content/uploads/2019/09/Netlify.png
  #     deploy_link: https://app.netlify.com/sites/3num-walrus/deploys/63d998369df8430008ef0991
  #   secrets:
  #     slack_webhook: ${{ secrets.RELEASE_SLACK_WEBHOOK }}
