name: simple
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install --immutable

      - run: echo "ROLLUP_TS_CACHE=$(yarn cache dir)/.rollup-ts-cache" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ${{ env.ROLLUP_TS_CACHE }}
          key: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}

      - run: cat "${ROLLUP_TS_CACHE}/hello" || true
      - run: mkdir -p "$ROLLUP_TS_CACHE" && echo $RANDOM >> "${ROLLUP_TS_CACHE}/hello"

    outputs:
      short_id: ${{ env.SHORT_ID }}
      deploy_link: ${{ env.DEPLOY_LINK }}

  # release:
  #   needs: build
  #   uses: ./.github/workflows/release-manager.yml
  #   with:
  #     name: floofy
  #     deploy_name: floofy container ${{ needs.build.outputs.short_id }}
  #     deploy_link: ${{ needs.build.outputs.deploy_link }}
  #   secrets:
  #     slack_webhook: ${{ secrets.RELEASE_SLACK_WEBHOOK }}
