name: simple
on:
  push:
    branches:
      - "main-never"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node_version: 18
          cache: npm
      - run: echo "SHORT_ID=ceb927dd" >> $GITHUB_ENV
      - run: echo "DEPLOY_LINK=https://dashboard.heroku.com/apps/lessor-stg/activity/releases/ceb927dd-bef1-4edf-b7bc-12484b0a6fba" >> $GITHUB_ENV
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=.next
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    outputs:
      short_id: ${{ env.SHORT_ID }}
      deploy_link: ${{ env.DEPLOY_LINK }}

  # release:
  #   needs: build
  #   uses: ./.github/workflows/release-manager.yml
  #   with:
  #     name: floofy
  #     deploy_name: floofy container ${{ needs.build.outputs.short_id }}
  #     deploy_link: ${{ needs.build.outputs.deploy_link }}
  #   secrets:
  #     slack_webhook: ${{ secrets.RELEASE_SLACK_WEBHOOK }}
