name: simple
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "hello-**"
    paths:
      - "**.js"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
      - run: git tag "hello-${RANDOM}"
