name: simple
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node_version: 18
          cache: npm

      - run: ls -al node_modules || true
      - run: npm install --frozen-lockfile
      - run: if [ -f node_modules/.cache/barf ]; then cat node_modules/.cache/barf; fi
      - run: mkdir -P node_modules/.cache/barf && echo $RANDOM >> node_modules/.cache/barf

    outputs:
      short_id: ${{ env.SHORT_ID }}
      deploy_link: ${{ env.DEPLOY_LINK }}

  # release:
  #   needs: build
  #   uses: ./.github/workflows/release-manager.yml
  #   with:
  #     name: floofy
  #     deploy_name: floofy container ${{ needs.build.outputs.short_id }}
  #     deploy_link: ${{ needs.build.outputs.deploy_link }}
  #   secrets:
  #     slack_webhook: ${{ secrets.RELEASE_SLACK_WEBHOOK }}
